###
GET http://localhost:8080/api/accounts
Authorization: Basic user secret

###
GET http://localhost:8080/api/accounts
Authorization: Basic admin secret

###
GET http://localhost:8080/api/accounts/1
Authorization: Basic user secret

###
GET http://localhost:8080/api/accounts/1
Authorization: Basic admin secret

###
GET http://localhost:8080/api/accounts/2
Authorization: Basic accountant secret

###
GET http://localhost:8080/api/accounts/3
Authorization: Basic accountant secret

###
GET http://localhost:8080/v3/api-docs
